Feat/challenge funcions 1
adlomo23/feat-challenge-funcions-1 pull request #1
Opened 2023-11-19 15:28 UTC by adlomo23

2023-11-19 20:21 UTC, tictools requested changes

2023-11-19 20:21 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +function getTotalWordsFromString(inputString) {
Do you know what type of expression is `/\s+/`? What is it evaluating? 

And `trim` method?

🤔

2023-11-19 20:21 UTC, tictools commented on exercise_03/generateRandomNumberInRange.js
> +        throw new Error('Invalid input: Limit must be a non-negative number.');
How do you control thrown error in `index.js`? 🤔

2023-11-19 20:21 UTC, tictools commented on exercise_04/isGreaterThan.js
> +        throw new Error('Invalid input: Both value and threshold must be numbers.');
How do you control thrown error in `index.js`? 🤔

2023-11-19 20:21 UTC, tictools commented on exercise_05/isAdditionGreaterThanFifty.js
> +        throw new Error('Invalid input: Both summand1 and summand2 must be numbers.');
How do you control thrown error in `index.js`? 🤔

2023-11-19 20:21 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
> +        throw new Error('Invalid input: Collection must be an array.');
How do you control thrown error in `index.js`? 🤔

2023-11-19 20:21 UTC, tictools commented on exercise_07/isTypeOf.js
> +        throw new Error('Invalid input: Type must be a string.');
How do you control thrown error in `index.js`? 🤔

More than that, it makes no sense in this case.

2023-11-20 18:46 UTC, adlomo23 commented on exercise_02/getTotalWordsFromString.js
> +function getTotalWordsFromString(inputString) {
It matches the whitespaces, and it put all characters consecutively.

2023-11-20 19:05 UTC, Enma1920 approved these changes
Good job!! Keep on working and you will succeed

2023-11-20 19:05 UTC, Enma1920 commented on exercise_03/generateRandomNumberInRange.js
> + * @param {limit} limit
must be {number} because you declare the type of parameter

2023-11-20 19:05 UTC, Enma1920 commented on exercise_05/index.js
add console.log(result) to know the result of the function, otherwise it will not return anything

2023-11-20 19:05 UTC, Enma1920 commented on exercise_06/checkCollectionHasElements.js
> + * @param {*} collection
@param {array} collection
@returns boolean

2023-11-20 19:05 UTC, Enma1920 commented on exercise_05/isAdditionGreaterThanFifty.js
> + * @returns
@param {number} summand1
@param {number} summand2
@returns boolean

2023-11-20 19:05 UTC, Enma1920 commented on exercise_04/isGreaterThan.js
> + * @returns
@param {number} value
@param {number} threshold
@returns boolean

2023-11-20 19:05 UTC, Enma1920 commented on exercise_06/index.js
console.log(result1);
console.log(result2);

2023-11-20 19:05 UTC, Enma1920 commented on exercise_07/isTypeOf.js
> + * @returns
@param {string | number | boolean | array} value
@param {boolean} type
@returns boolean

2023-11-20 19:05 UTC, Enma1920 commented on package.json
>    },
add inside scripts{

    "lint": "prettier . --check",
    "lint:fix": "prettier . --write"
}

2023-11-21 19:03 UTC, tictools approved these changes

2023-11-21 19:04 UTC, merged